### PR TITLE
added redirect to login

### PR DESCRIPTION
**Pull request by ordinarylif3**
Added redirect and account page for login

### CODE REVIEW

**Comment by reedmarohn** [comment]
It would be nice to implement an Admin vs. Regular User routing for these redirects, but current commits LGTM

**Comment by rcamwm** [comment]
It looks like logging in won't send an alert anymore. Is this correct? If so, is there any way to fix this issue?

**Comment by ordinarylif3** [comment]
> 

I will try to implement that this weekend with different auth level for user and admin

**Comment by ordinarylif3** [comment]
> It looks like logging in won't send an alert anymore. Is this correct? If so, is there any way to fix this issue?

The alert was removed since we need to revamp the login/signup page with functions rather than a class.

**Comment by seena18** [comment]
you can make the login auth with the database

**Pull request merged**
