### PR TITLE
Added reset button

### PR DESCRIPTION
**Pull request by rcamwm**
Added a reset button that works to (re)initialize the pixel database. If there are no pixels in the database, they'll be added. If there are pixels, they'll all be deleted and new blank ones will be added in their place.

Updated front end canvas to automatically display changes to pixels in database, allowing multiple users to work on the same canvas and see each others' changes in real time.

### CODE REVIEW

**Review by ordinarylif3 — COMMENTED** [review]
The functions that were in pixel.js that change the pixel color when I hover over it with my mouse are gone. Is there any way that we can keep that feature while still having pixels updated with the database properly?

**Comment by rcamwm** [comment]
> The functions that were in pixel.js that change the pixel color when I hover over it with my mouse are gone. Is there any way that we can keep that feature while still having pixels updated with the database properly?

Unfortunately I couldn't figure out a way to keep that feature. Before, there were several useStates inside of Pixel.js that determined what color was currently being displayed, depending on if the mouse was hovering over the pixel component or not. For whatever reason, these useStates weren't updating when new data was sent up from the backend. However, the issue was fixed when I removed them and set the pixel component's color directly to the pixel data from the backend instead. 

Ideally I would prefer we didn't lose this feature as well, but with our limited time left on the project I felt that it was more important to just get the canvas updating automatically. I'll create a new issue for our backlog to see if we can get this feature back up.

**Comment by reedmarohn** [comment]
Is there going to be any problems with how the canvas looks if you use the reset button while it's automatically updating the front? Since the reset button actually deletes every pixel and then re-adds new ones, might need to see if it still looks fine.

**Comment by seena18** [comment]
I added the interval in a previous commit. Get requests in a loop are very resource intensive, don't get rid of my timer.

**Comment by rcamwm** [comment]
> I added the interval in a previous commit. Get requests in a loop are very resource intensive, don't get rid of my timer.

👍🏻

**Pull request merged**
